### ISSUE TITLE
"useRelativeCover = true" is not working for me

### ISSUE THREAD

**Issue by aormsby** [panr/hugo-theme-hello-friend#103]
I've tried to add `useRelativeCover = true` to multiple posts with different image files, but I always get a broken image icon. Only the absolute link resolves correctly. Code seems unchanged since the pull request that added it. Is there any reason it would just fail like that?

**Comment by panr** [comment]
I don't remember exactly how it works, but... did you put image inside a post folder?
LIke:

```
- my-post-example
  |- image.png
  |- index.md
```

**Comment by aormsby** [comment]
Ahhhh crap, I hadn't named the post file `index.md`. It actually works fine if it's that way, but not if I name the file something like `my-post.md`. It even allows relative URLs in the post automatically...... I had been wondering why I couldn't do that before.

I gotta say, I've had more trouble than I thought I would understanding the conventions of Hugo's page bundling system. Everything is just **_so specific_**, and if any one thing is placed or named differently than expected the whole system falls apart. I'm honestly starting to wonder why I'm finding these little things so difficult to figure out. I guess I'm just not used to it yet.

In any case, things _seem_ to be okay for the moment. Thanks for being so responsive about this stuff.

Somewhat related question - is there any way to set the size of the cover image? It seems based in the width limit of the content area, and It's awfully large for images that are taller than they are wide.

**Comment by panr** [comment]
> Ahhhh crap, I hadn't named the post file index.md. It actually works fine if it's that way, but not if I name the file something like my-post.md.

Basically it's how routing works by default. When you have a folder with custom name and index.[whatever] file inside, this file will read as... well... index. For example, a site with `my-own-domain.com` — in your folder structure you have `index.html` file, so when you go to `https://my-own-domain.com` browser will read this `index.html` file. You don't need to type `https://my-own.domain.com/index.html` ;-) So how Hugo works seems to be OK.

> Somewhat related question - is there any way to set the size of the cover image? It seems based in the width limit of the content area, and It's awfully large for images that are taller than they are wide.

By default... no. But... you can do a little tick. Omit cover prop and pass one of built-in shortcodes `figure`, `image` (for these just add some `style` data) or `imageproc` — https://github.com/panr/hugo-theme-hello-friend#built-in-shortcodes.

> Thanks for being so responsive about this stuff.

If I can be honest, you were lucky, because I had finally some time to look at my open source projects 🙏 😎

**Comment by aormsby** [comment]
> Basically it's how routing works by default.

Now that you explain this, I realize it totally makes sense.

I'm not much of a web dev, honestly. My focus has been more on games in the past, though I'm just coming off long break from that and getting into mobile apps (and perhaps back into games lol). I wanted to make a new website for myself and came across Hugo, and it looked so straightforward! I suppose it would be if I had more basic knowledge of some things. That said, I'm really enjoying tinkering with it and picking up all the knowledge that comes with it. So I do really appreciate you taking the time to explain some things - even simple things!

> Omit cover prop and pass one of built-in shortcodes...

Do you mean just as the first image in the post? I'll definitely try that out, thanks!
