### ISSUE TITLE
How to set pagination on archive page?

### ISSUE THREAD

**Issue by eallion** [panr/hugo-theme-hello-friend#157]
How to set pagination on archive page?
thanks

**Comment by eallion** [comment]
too many posts in my blog 
[https://eallion.com/archives/](https://eallion.com/archives/)

**Comment by guilhermesteves** [comment]
Wow, you write a lot, I'll look into it

**Comment by aormsby** [comment]
Hey, there's a great active example in `layouts/_default/list.html`. The main post list layout uses pagination, and it's only a few extra lines of code.

https://github.com/panr/hugo-theme-hello-friend/blob/670dc85b070ea96d8e3a0636b375a887fba3db6b/layouts/_default/list.html#L9-L12
`...inner list layout code here...`
https://github.com/panr/hugo-theme-hello-friend/blob/670dc85b070ea96d8e3a0636b375a887fba3db6b/layouts/_default/list.html#L60-L62

The main list layout code is just wrapped in the `range` using the `paginator` value. It's been a while since I looked at this, but I don't think you even have to change anything to make this work in the archive layout. Just copy-paste the `paginator` line and wrap the `range` around the archive layout data. Copying the way the list layout does this is a great place to start.

[There's more info on pagination in the Hugo docs](https://gohugo.io/templates/pagination/) if you want to do something more.

Good luck!

**Comment by eallion** [comment]
> Wow, you write a lot, I'll look into it

**Comment by eallion** [comment]
> Hey, there's a great active example in `layouts/_default/list.html`. The main post list layout uses pagination, and it's only a few extra lines of code.
> 
> https://github.com/panr/hugo-theme-hello-friend/blob/670dc85b070ea96d8e3a0636b375a887fba3db6b/layouts/_default/list.html#L9-L12
> 
> 
> `...inner list layout code here...`
> https://github.com/panr/hugo-theme-hello-friend/blob/670dc85b070ea96d8e3a0636b375a887fba3db6b/layouts/_default/list.html#L60-L62
> 
> The main list layout code is just wrapped in the `range` using the `paginator` value. It's been a while since I looked at this, but I don't think you even have to change anything to make this work in the archive layout. Just copy-paste the `paginator` line and wrap the `range` around the archive layout data. Copying the way the list layout does this is a great place to start.
> 
> [There's more info on pagination in the Hugo docs](https://gohugo.io/templates/pagination/) if you want to do something more.
> 
> Good luck!



> Hey, there's a great active example in `layouts/_default/list.html`. The main post list layout uses pagination, and it's only a few extra lines of code.
> 
> https://github.com/panr/hugo-theme-hello-friend/blob/670dc85b070ea96d8e3a0636b375a887fba3db6b/layouts/_default/list.html#L9-L12
> 
> 
> `...inner list layout code here...`
> https://github.com/panr/hugo-theme-hello-friend/blob/670dc85b070ea96d8e3a0636b375a887fba3db6b/layouts/_default/list.html#L60-L62
> 
> The main list layout code is just wrapped in the `range` using the `paginator` value. It's been a while since I looked at this, but I don't think you even have to change anything to make this work in the archive layout. Just copy-paste the `paginator` line and wrap the `range` around the archive layout data. Copying the way the list layout does this is a great place to start.
> 
> [There's more info on pagination in the Hugo docs](https://gohugo.io/templates/pagination/) if you want to do something more.
> 
> Good luck!

Thanks a lot! But im a new Hugoer, i will try this.

**Comment by eallion** [comment]
I solved it.
https://github.com/eallion/eallion.com/blob/main/themes/hello-friend/layouts/archives/list.html
https://github.com/eallion/eallion.com/commit/cd65335e9ae1ed7803e673274f3ce091524b5cfa
