### ISSUE TITLE
Changing the way we show different languages

### ISSUE THREAD

**Issue by avronr** [panr/hugo-theme-hello-friend#164]
Hey, right now we use flags of various counties to indicate various languages in which a post is available. But in certain counties like India which is where I am from, we have multiple vernacular languages. So If I want to add support for 2 such languages from my country I'll have to use the same flag for both languages which doesn't help differentiate them. Can we address this issue somehow @panr .

Thanks.

**Comment by aormsby** [comment]
Wow, this is a great question! I'm getting into the field of localization, and I'd love to help find a good solution for this issue. I agree that flags can often be a poor indicator of language and culture, and it would be nice to add more details to them or to move to better options if any are available.

I haven't enabled i18n on my site yet, so I have a few questions to understand how things are set up.

1. Is the flag selection built into Hugo's i18n module? Or is it part of this theme?
2. How do we edit the selection data to add to the supported languages? And is it customizable in a way that allows us to add more details (like text)?

I'm working on a mobile app that also has a language selector, and instead of using flags, I decided to display local language names in a dropdown so users could comfortably identify and select the language they want from a list of supported languages. Something like this:

- English
- español
- 日本語
- தமிழ்
- dansk
- [(source)](https://www.omniglot.com/language/names.htm)

In my app's situation, I think this helps get around the issue of nationality vs. culture. However, I haven't implemented it yet, and I think I may have to deal with font-related display issues, which could be a minor roadblock. This may or may not be an issue depending on what characters the theme font can display.

In any case, I haven't spent any time with Hugo's i18n to be sure yet if this is achievable, so I need to learn more about it first. I'm excited to help, though!

I'd love to hear thoughts on this idea as well as other possible solutions. 🙂

**Comment by avronr** [comment]
This is a fork of the same theme. They too use the same method.
https://github.com/rhazdon/hugo-theme-hello-friend-ng/tree/master/i18n

**Comment by panr** [comment]
@avronr could you give us a link to this site. I'm a little confused, because I don't know what _exactly_  do you want to achieve and how this is related to the theme 🤔

**Comment by avronr** [comment]
Sorry about this. But I assumed this theme had support for localisation like [this one](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/README.md) which is a fork of your theme. I assumed this feature was available in your theme too but now I see that it isn't. Sorry for the trouble. Closing the issue.

**Comment by aormsby** [comment]
Well, that explains why I haven't seen those flags!

@panr It's amazing how often the 'ng' confusion happens! It feels sort of like a running joke now.

In any case, I'll still do something like this for my site (eventually) and will share to see if you want it.

**Comment by panr** [comment]
> @panr It's amazing how often the 'ng' confusion happens! It feels sort of like a running joke now.

Yeah... It's starting to annoy me a little and I have mixed feelings about that fork 😕
