### ISSUE TITLE
Adding custom scripts in index.js won't work

### ISSUE THREAD

**Issue by SurajVerma** [panr/hugo-theme-hello-friend#170]
First of all, thank you very much for the theme. It's awesome.
I am new to Hugo, and recently moved my Jekyll blog to Hugo.

I am trying to add some custom JavaScript in `index.js` but it is not working, am I supposed to add custom scripts in `main.js` ? If yes, then what is the use of `index.js` as the comments here says `// Add your script here`.

Also, this may be out of the scope of theme but wanted to know how to make the build minify theme JS and CSS files as well as `--minify` doesn't for it.

**Comment by panr** [comment]
- `index.js` works only with webpack, when you recompile the theme. It's my bad, I described it poorly (I'm gonna fix it).
  - to make it work, you have to add some code into the `index.js` and then run `yarn dev` (for dev purpose) or `yarn build` to create minified code of the theme. This should work as you expected then.

But you can add your own JS code without all these recompilation steps. Use `extended_footer.html` (or `extended_head.html` if you need to run code before `body`). Take a look at **Extended...** part of https://github.com/panr/hugo-theme-hello-friend#add-ons. This partial should be created inside _your_ build, not the theme itself, since Hugo can read those files directly from your home directory — https://gohugo.io/templates/lookup-order/.

**Comment by SurajVerma** [comment]
Thanks @panr, that's what I needed to know.
