### ISSUE TITLE
possibility of adding social networks and links

### ISSUE THREAD

**Issue by ccantos** [panr/hugo-theme-hello-friend#18]
your theme is awesome Is there the possibility of adding icons with social networks with their respective icons ?. for example twitter. At the end of the page in the "footer" you have enough space for it.
Another idea is the possibility of adding both _logoText_ and _.svg_ at the same time in _[params.logo]_.
Anyway, I love your theme. My congratulations!

**Comment by panr** [comment]
HI @ccantos I'm glad you like the theme 😎 
In case of social icons — I'm not a big fan of these... that's why the theme doesn't have them. 

The good news is... that with Hugo, you can override some layout files. Footer for example — https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/footer.html. 

Just create a copy of the file in your root dir — `[your root dir]/layouts/partials/footer.html` and add whatever you want ;-) If you want to have both logo icon and default logo of the theme, please change code in your newly created file in this particular line https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/footer.html#L6. You can alse copy `.../logo.html` file and change condition of the logo appearance or create a new one from the scratch 👌🏻

**Comment by ccantos** [comment]
thank you very much for your help :dancer:
