### ISSUE TITLE
When generating site duplicating menu items

### ISSUE THREAD

**Issue by mebored81** [panr/hugo-theme-hello-friend#46]
Looks all fine when in local mode but when I am generating the site to upload to my server is duplicating the menu items and the dark/light mode icon is disappearing.

**Comment by panr** [comment]
@mebored81 hmm... could you attach a screenshot?

Everything should me fine after you upload the site to your server. It's all about the base path.
Change `baseurl = "/"` to `baseurl = ""` in config file and regenerate site. This time everything should look like intended. 

Probably the issue occurs to you because of the lack of styling (browser console should throw errors) when you generate `static` and run files locally. Paths to resources should be "broken"...

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1303365/54882848-8f533c80-4e5e-11e9-9e9c-a8e50a93b187.png">

(I use two separate menus (with different structure). `hidden` class doesn't apply to one of these...)
